server:
  port: 8088

spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC&autoReconnect=true
    password: 510726

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl